# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Aug  5 21:32:01 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QGraphicsScene
from pyqtgraph import PlotWidget
from pyqtgraph import GraphicsLayoutWidget
import pyqtgraph as pg
from pyqtgraph.Point import Point

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 713)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1361, 691))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Spectra = QtGui.QWidget()
        self.Spectra.setObjectName(_fromUtf8("Spectra"))
        self.layoutWidget = QtGui.QWidget(self.Spectra)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 5, 1343, 623))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(428, 114))
        self.frame.setMaximumSize(QtCore.QSize(428, 114))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 3)
        self.checkBoxinf_1 = QtGui.QCheckBox(self.frame)
        self.checkBoxinf_1.setChecked(False)
        self.checkBoxinf_1.setAutoExclusive(False)
        self.checkBoxinf_1.setObjectName(_fromUtf8("checkBoxinf_1"))
        self.gridLayout.addWidget(self.checkBoxinf_1, 1, 0, 1, 2)
        self.radioButtoncomma_1 = QtGui.QRadioButton(self.frame)
        self.radioButtoncomma_1.setChecked(True)
        self.radioButtoncomma_1.setObjectName(_fromUtf8("radioButtoncomma_1"))
        self.gridLayout.addWidget(self.radioButtoncomma_1, 1, 2, 1, 2)
        self.radioButtonspace_1 = QtGui.QRadioButton(self.frame)
        self.radioButtonspace_1.setObjectName(_fromUtf8("radioButtonspace_1"))
        self.gridLayout.addWidget(self.radioButtonspace_1, 1, 4, 1, 2)
        self.radioButtoncolon_1 = QtGui.QRadioButton(self.frame)
        self.radioButtoncolon_1.setObjectName(_fromUtf8("radioButtoncolon_1"))
        self.gridLayout.addWidget(self.radioButtoncolon_1, 1, 6, 1, 1)
        self.checkBoxspectra_1 = QtGui.QCheckBox(self.frame)
        self.checkBoxspectra_1.setObjectName(_fromUtf8("checkBoxspectra_1"))
        self.gridLayout.addWidget(self.checkBoxspectra_1, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 1)
        self.openButton_1 = QtGui.QPushButton(self.frame)
        self.openButton_1.setObjectName(_fromUtf8("openButton_1"))
        self.gridLayout.addWidget(self.openButton_1, 3, 0, 1, 1)
        self.calculateButton_1 = QtGui.QPushButton(self.frame)
        self.calculateButton_1.setObjectName(_fromUtf8("calculateButton_1"))
        self.gridLayout.addWidget(self.calculateButton_1, 3, 1, 1, 4)
        self.saveButton_1 = QtGui.QPushButton(self.frame)
        self.saveButton_1.setObjectName(_fromUtf8("saveButton_1"))
        self.gridLayout.addWidget(self.saveButton_1, 3, 5, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 7, 2, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(888, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.layoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(1341, 501))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Plot1_1 = PlotWidget(self.frame_2)
        self.Plot1_1.setObjectName(_fromUtf8("Plot1_1"))
        self.gridLayout_2.addWidget(self.Plot1_1, 0, 0, 1, 1)
        self.Plot2_1 = PlotWidget(self.frame_2)
        self.Plot2_1.setObjectName(_fromUtf8("Plot2_1"))
        self.gridLayout_2.addWidget(self.Plot2_1, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Spectra, _fromUtf8(""))
        self.Spectra_analysis = QtGui.QWidget()
        self.Spectra_analysis.setObjectName(_fromUtf8("Spectra_analysis"))
        self.layoutWidget1 = QtGui.QWidget(self.Spectra_analysis)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 13, 1337, 611))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame_4 = QtGui.QFrame(self.layoutWidget1)
        self.frame_4.setMinimumSize(QtCore.QSize(351, 61))
        self.frame_4.setMaximumSize(QtCore.QSize(351, 61))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushButtonImport_2 = QtGui.QPushButton(self.frame_4)
        self.pushButtonImport_2.setGeometry(QtCore.QRect(10, 10, 111, 24))
        self.pushButtonImport_2.setAutoFillBackground(False)
        self.pushButtonImport_2.setObjectName(_fromUtf8("pushButtonImport_2"))
        self.radioButtonFrmclc_2 = QtGui.QRadioButton(self.frame_4)
        self.radioButtonFrmclc_2.setGeometry(QtCore.QRect(120, 10, 131, 21))
        self.radioButtonFrmclc_2.setChecked(True)
        self.radioButtonFrmclc_2.setObjectName(_fromUtf8("radioButtonFrmclc_2"))
        self.radioButtonFrmcsv_2 = QtGui.QRadioButton(self.frame_4)
        self.radioButtonFrmcsv_2.setGeometry(QtCore.QRect(120, 30, 97, 21))
        self.radioButtonFrmcsv_2.setObjectName(_fromUtf8("radioButtonFrmcsv_2"))
        self.pushButtonSave_2 = QtGui.QPushButton(self.frame_4)
        self.pushButtonSave_2.setGeometry(QtCore.QRect(250, 10, 94, 24))
        self.pushButtonSave_2.setObjectName(_fromUtf8("pushButtonSave_2"))
        self.pushButtonReset_2 = QtGui.QPushButton(self.frame_4)
        self.pushButtonReset_2.setGeometry(QtCore.QRect(250, 30, 94, 24))
        self.pushButtonReset_2.setObjectName(_fromUtf8("pushButtonReset_2"))
        self.gridLayout_6.addWidget(self.frame_4, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(978, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.layoutWidget1)
        self.frame_3.setMinimumSize(QtCore.QSize(1335, 542))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.Plot1_2 = PlotWidget(self.frame_3)
        self.Plot1_2.setMinimumSize(QtCore.QSize(1258, 528))
        self.Plot1_2.setMouseTracking(False)
        self.Plot1_2.setObjectName(_fromUtf8("Plot1_2"))
        self.gridLayout_5.addWidget(self.Plot1_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Spectra_analysis, _fromUtf8(""))
        self.Results = QtGui.QWidget()
        self.Results.setObjectName(_fromUtf8("Results"))
        self.graphicsView = QtGui.QGraphicsView(self.Results)
        self.graphicsView.setGeometry(QtCore.QRect(490, 10, 851, 641))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.tableWidget = QtGui.QTableWidget(self.Results)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 471, 641))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(155)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.Results, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FT-I.R. Analysis Tool", None))
        self.label.setText(_translate("MainWindow", "Select Source Data Type:", None))
        self.label_2.setText(_translate("MainWindow", "Csv Delimiter:", None))
        self.checkBoxinf_1.setText(_translate("MainWindow", "Spectra to Interferogram", None))
        self.radioButtoncomma_1.setText(_translate("MainWindow", "Comma ", None))
        self.radioButtonspace_1.setText(_translate("MainWindow", "Space", None))
        self.radioButtoncolon_1.setText(_translate("MainWindow", "Colon", None))
        self.checkBoxspectra_1.setText(_translate("MainWindow", "Interferrogram to Spectra", None))
        self.openButton_1.setText(_translate("MainWindow", "Open csv Source File", None))
        self.calculateButton_1.setText(_translate("MainWindow", "Calculate", None))
        self.saveButton_1.setText(_translate("MainWindow", "Save Result", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Spectra),
                                  _translate("MainWindow", "Spectra Calculations", None))
        self.pushButtonImport_2.setText(_translate("MainWindow", "Import Data", None))
        self.radioButtonFrmclc_2.setText(_translate("MainWindow", "From Calculation", None))
        self.radioButtonFrmcsv_2.setText(_translate("MainWindow", "From Csv", None))
        self.pushButtonSave_2.setText(_translate("MainWindow", "Save Result", None))
        self.pushButtonReset_2.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Spectra_analysis),
                                  _translate("MainWindow", "Peak Picking Tool", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Wavenumber(1/cm)", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Relative Intensity", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zone", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Results), _translate("MainWindow", "Results", None))

        # hide unused components temporararily
        self.Plot1_1.clear()
        self.Plot2_1.clear()
        self.Plot1_1.hide()
        self.Plot2_1.hide()
        self.Plot1_2.hide()
        self.tabWidget.setTabEnabled(2, False)
        self.radioButtonFrmclc_2.setEnabled(False)
        self.pushButtonSave_2.setEnabled(False)